name: 231webdev
favicon: null
layout_spectrum: 0.46933728619478643
typography_spectrum: 0.43840043619275093
title: Jeremiah the Dreamers GridSite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040707'
    - '#ffffff'
    - '#356568'
    - '#54a3d9'
    - '#bfbfbf'
  brandStrength: 0.5
  lightness: 0.26709464844316244
  saturation: 0.342981027206406
  rhythmicContrast: 0.529985505156219
purpose: []
